# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.cache/wt [current_project]
set_property parent.project_path /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/carry_lookahead_sub/carry_lookahead_adder.srcs/sources_1/new/4bit_CLA.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/CLA_258/CLA_258.srcs/sources_1/new/CLA_258.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/CLA_258/CLA_258.srcs/sources_1/new/CLA_258_top.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/new/CLS.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/carry_save_adder/carry_save_adder.srcs/sources_1/new/CSA.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/LUT/LUT.srcs/sources_1/new/LUT.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/mod_mult_loop_cont/mod_mult_loop_cont.srcs/sources_1/new/mod_mult.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/imports/Design_of_Digital_Systems1_RSA/r_shift_reg/r_shift_reg.srcs/sources_1/new/r_shift_reg.vhd
  /home/gabor7669/Desktop/DoDS1/Design_of_Digital_Systems1_RSA/FM_Mod_Mult/FM_Mod_Mult.srcs/sources_1/new/FM_Mod_Mult.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top FM_Mod_Mult -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FM_Mod_Mult.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FM_Mod_Mult_utilization_synth.rpt -pb FM_Mod_Mult_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
